In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
from numpy import linalg as LA
import json
import math
%matplotlib inline
import matplotlib.pyplot as plt

In [3]:
with open("final.json") as f:
    data = json.load(f)
    
num_jokes = len(data)
print("Loaded {} jokes".format(num_jokes))
print("Each joke has the following keys:")
print(data[0].keys())

# joke_to_index = {joke_idx:index for index, joke in enumerate([d['joke'] for d in data])}
# index_to_joke = {idx:joke for idx, joke in enumerate([d['joke'] for d in data])}

Loaded 6600 jokes
Each joke has the following keys:
dict_keys(['joke', 'score', 'categories'])


In [4]:
n_feats = 5000
doc_by_vocab = np.empty([len(data), n_feats])

def build_vectorizer(max_features, stop_words, max_df=0.8, min_df=10, norm='l2'):
    """Returns a TfidfVectorizer object with the above preprocessing properties.
    
    Note: This function may log a deprecation warning. This is normal, and you
    can simply ignore it.
    
    Params: {max_features: Integer,
             max_df: Float,
             min_df: Float,
             norm: String,
             stop_words: String}
    Returns: TfidfVectorizer
    """
    # YOUR CODE HERE
    return TfidfVectorizer(max_features = max_features, stop_words = stop_words, max_df = 0.8, min_df = 10, norm='l2')

In [5]:
tfidf_vec = build_vectorizer(n_feats, "english")
doc_by_vocab = tfidf_vec.fit_transform([d['joke'] for d in data]).toarray()
index_to_vocab = {i:v for i, v in enumerate(tfidf_vec.get_feature_names())}

In [6]:
print(doc_by_vocab)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
print(tfidf_vec.get_feature_names())

['00', '000', '10', '100', '1000', '11', '12', '120', '13', '14', '15', '150', '16', '17', '18', '19', '1st', '20', '200', '2000', '2001', '21', '22', '23', '24', '25', '250', '26', '27', '28', '29', '2nd', '30', '300', '31', '32', '33', '34', '35', '36', '365', '37', '38', '39', '3rd', '40', '41', '42', '43', '44', '45', '46', '47', '49', '4th', '50', '500', '51', '52', '55', '58', '5th', '60', '69', '70', '72', '75', '7th', '80', '85', '8th', '90', '95', '98', '99', '9th', 'abe', 'ability', 'able', 'abraham', 'absolutely', 'accept', 'acceptable', 'accepted', 'access', 'accident', 'accidentally', 'accompanied', 'according', 'account', 'accountant', 'acid', 'act', 'acting', 'action', 'actions', 'active', 'activities', 'activity', 'acts', 'actual', 'actually', 'ad', 'adam', 'add', 'added', 'adding', 'addition', 'additional', 'address', 'addressed', 'administration', 'administrator', 'admire', 'admit', 'admits', 'admitted', 'ads', 'adult', 'adults', 'advance', 'advanced', 'advantage', 'a

In [9]:
print(len(tfidf_vec.get_feature_names()))

4129


In [8]:
print(data[0])

{'joke': 'Whenever you feel sad... It helps to picture that somewhere in this world, there’s a fool pulling on a door that says “PUSH”!', 'score': None, 'categories': []}
